[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"

[functions]
  external_node_modules = ["square"]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[context.production]
  command = "python --version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200