import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight, Award, CheckCircle, TrendingUp } from 'lucide-react';
export default function Hero({ onConsultationClick }) {
    const scrollToTestimonials = () => {
        const element = document.getElementById('testimonials');
        element?.scrollIntoView({ behavior: 'smooth' });
    };
    return (_jsxs("div", { className: "relative bg-gradient-to-r from-blue-600 to-blue-800 pt-24", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20", children: _jsxs("div", { className: "grid md:grid-cols-2 gap-12 items-center", children: [_jsxs("div", { className: "text-white", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-bold leading-tight mb-6", children: "Expert Grant Writing & Government Contract Solutions" }), _jsx("p", { className: "text-xl text-blue-100 mb-8", children: "Professional grant writing and government proposal services backed by decades of experience and proven expertise." }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4", children: [_jsxs("button", { onClick: onConsultationClick, className: "bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-blue-50 transition-colors flex items-center justify-center", children: ["Start Free Consultation", _jsx(ArrowRight, { className: "ml-2 h-5 w-5" })] }), _jsx("button", { onClick: scrollToTestimonials, className: "border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white/10 transition-colors text-center", children: "View Success Stories" })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white/10 backdrop-blur-lg p-6 rounded-xl", children: [_jsx(Award, { className: "h-10 w-10 text-yellow-400 mb-4" }), _jsx("h3", { className: "text-white text-lg font-semibold mb-2", children: "Proven Track Record" }), _jsx("p", { className: "text-blue-100", children: "Consistent success in securing funding" })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-lg p-6 rounded-xl", children: [_jsx(CheckCircle, { className: "h-10 w-10 text-green-400 mb-4" }), _jsx("h3", { className: "text-white text-lg font-semibold mb-2", children: "Expert Team" }), _jsx("p", { className: "text-blue-100", children: "Former grant reviewers & proposal writers" })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-lg p-6 rounded-xl", children: [_jsx(TrendingUp, { className: "h-10 w-10 text-purple-400 mb-4" }), _jsx("h3", { className: "text-white text-lg font-semibold mb-2", children: "15+ Years" }), _jsx("p", { className: "text-blue-100", children: "Of industry expertise" })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-lg p-6 rounded-xl", children: [_jsx(Award, { className: "h-10 w-10 text-orange-400 mb-4" }), _jsx("h3", { className: "text-white text-lg font-semibold mb-2", children: "500+ Clients" }), _jsx("p", { className: "text-blue-100", children: "Across various sectors" })] })] })] }) }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-white to-transparent" })] }));
}
